import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { isToolCallEventType } from "@earendil-works/pi-coding-agent";

/**
 * Example: Custom validation policies
 *
 * This extension enforces project-specific rules:
 * - Block writes to generated/ directories
 * - Require --coverage flag for test commands
 * - Enforce file naming conventions
 *
 * Install:
 * 1. Copy this file to ~/.pi/agent/extensions/custom-policies.ts
 * 2. Add to .pi/capstan.json:
 *    {
 *      "safetyGuardPath": "~/.pi/agent/extensions/custom-policies.ts"
 *    }
 */

export default function(pi: ExtensionAPI) {
  // Block writes to generated files
  pi.on("tool_call", (event) => {
    if (isToolCallEventType("write", event) || isToolCallEventType("edit", event)) {
      const path = event.input.path;

      // Block generated directories
      if (path.includes("/generated/") || path.includes("/__generated__/")) {
        return {
          block: true,
          reason: "Cannot write to generated files. These are auto-generated by the build system."
        };
      }

      // Enforce naming conventions for components
      if (path.includes("/components/") && path.endsWith(".tsx")) {
        const filename = path.split("/").pop() || "";
        if (filename[0] !== filename[0]?.toUpperCase()) {
          return {
            block: true,
            reason: "React component files must start with uppercase letter"
          };
        }
      }

      // Block modifications to lock files (should use package manager)
      if (path.endsWith("package-lock.json") && !path.includes("capstan")) {
        return {
          block: true,
          reason: "Do not manually edit package-lock.json. Use npm install instead."
        };
      }
    }

    // Require coverage flag for tests
    if (isToolCallEventType("bash", event)) {
      const cmd = event.input.command;

      // Enforce test coverage
      if ((cmd.includes("npm test") || cmd.includes("yarn test")) &&
          !cmd.includes("--coverage") &&
          !cmd.includes("--watch")) {
        return {
          block: true,
          reason: "Tests must run with --coverage flag. Use: npm test -- --coverage"
        };
      }

      // Block direct git operations (capstan manages git)
      if (cmd.match(/\bgit\s+(add|commit|push|merge|rebase)/)) {
        return {
          block: true,
          reason: "Do not use git commands directly. Capstan manages git operations."
        };
      }

      // Warn about dangerous operations
      if (cmd.includes("rm -rf") && !cmd.includes("node_modules")) {
        return {
          block: true,
          reason: "Dangerous rm -rf detected. Please be more specific about what to delete."
        };
      }
    }
  });

  // Custom validation on session start
  pi.on("session_start", () => {
    console.log("[CustomPolicies] Project-specific validation policies loaded");
  });
}
